# Turn off email notifications
notifications:
  email: false

language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Additional services
services:
  - postgresql

# Set config for testing on Travis
env:
  global:
    - SECRET_KEY=96da21865b3e3774d7b2f0cb15cf5ee4f7c1ce09042745ca
    - DEBUG=True
    - PGPORT=5433
    - DATABASE_URI='postgresql://postgres@localhost:5433/weconnect'

before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3

before_script:
  - psql -c 'create database weconnect_test;' -U postgres

# command to run tests.py
script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=api
  - coveralls
  - codecov

after_sucess:
  - "coveralls"
  - "codecov"